### ISSUE TITLE
Question about using Antox

### ISSUE THREAD

**Issue by darkman088** [Astonex/Antox#641]
Hello,

I have recently become a tox fan and I finally decided to try it out on my Android phone as well.
Just there are some things, which I wasn't able to figure out, so like every noob, I'm gonna ask
questions :-)
1) How is this supposed to work, when I already have a tox account ? I was able to transfer a file, called data between uTox and qTox on a PC, so I could use the same account under both clients... So how am I supposed to do this with Antox ? I did not see any directory on my phone, where I could copy this file.
2) I did not see the buttons Copy ID, if I want to easily send my tox ID to anyone. I also think that it will not be possible to paste someone's ID while adding a contact... Or at least it wasn't clear to me on the first glance. Typing such a long string like the tox ID will be atrocious and quite subtle to typos. What is the solution to all this please ?

Many thanks!

**Comment by darkman088** [comment]
Hello,

please kindly let me know how has this been closed ? Has the missing function been implemented ? Thank you!

**Comment by Astonex** [comment]
Exporting your profile has been added. You can find it at the bottom of the Profile activity. 

You can import a profile when you are creating a new one.

**Comment by v6** [comment]
// , I just exported my profile, but it doesn't seem to show up in the directory I selected with "Select Directory". 

I have version 0.22.
