### ISSUE TITLE
low-traffic mode for mobile internet connections

### ISSUE THREAD

**Issue by rubo77** [Astonex/Antox#672]
Antox uses too much traffic on mobile connection.

I let Antox run a few days on my mobile internet connection on my cellphone and it used 400MB by just running. No file transfers or such.

There should be a low-traffic mode for mobile internet connections

**Comment by Astonex** [comment]
This is a problem with the tox core and there isn't too much that can be done by the clients to limit bandwidth unfortunately. You'll need to open an issue in the toxcore repo.

**Comment by rubo77** [comment]
Couldn't you for example set a timer, if there isn't said anything you disconnect and reconnect only every few minutes for a few seconds to catch new messages?

Or you set the allowed internet bandwidth for antox down to a very low amount if nothing is said for a while
