### ISSUE TITLE
Get the APK from the Readme link is broken (404 error)

### ISSUE THREAD

**Issue by mickours** [Astonex/Antox#673]
Hello I want to try Antox but the link to get the APK on the Readme is not working.
The link:
https://jenkins.libtoxcore.so/job/Android-Antox/lastSuccessfulBuild/artifact/antox.apk

The  page content:
HTTP ERROR 404

Problem accessing /job/Android-Antox/lastSuccessfulBuild/artifact/antox.apk. Reason:

    Not Found

Powered by Jetty://

**Comment by LumenTeun** [comment]
I suspect that jenkins has stopped building APKs because Antox is abandoned. There's still an APK on [Astonex's F-Droid repo](https://markwinter.me/fdroid/repo/antox.apk) if you want to try it out.

**Comment by mickours** [comment]
Thanks for the link. :)
Any maintainer to confirm that the project is abandoned?
Any plan fort thé futur of this app (that seems pretty good)?

**Comment by blightwing** [comment]
Wow this is an abandoned project? That seriously sucks.  I've been using Tox on every platform but android waiting for this to come out of alpha. How disappointing. I had a whole squad of tech support agents psyched about Tox and AnTox too.

**Comment by dcharles525** [comment]
@blightwing Tox is still very active, Antox is just dead, for now. There might be a rewrite of the app in the future though! (Fingers crossed)

**Comment by urras** [comment]
For those not already aware, a working official fork of Antox is being maintained at [subliun/Antox](https://github.com/subliun/Antox)
