### ISSUE TITLE
Can't send file from Antox to qTox

### ISSUE THREAD

**Issue by Polynomdivison** [Astonex/Antox#675]
Hi,
I'm not able to send files from Antox to qTox.
Error Message: "Cannot send file to offline frriend"
Antox correctly displays that I'm online, but the file transfer doesn't work.
But I'm able to send files from qTox to Antox!

Version 0.22

**Comment by dethstar** [comment]
This project is no longer being maintained for various reasons. There is a working and maintained fork of Antox https://github.com/subliun/Antox
