### ISSUE TITLE
Offline messages are not sent when contact is back online

### ISSUE THREAD

**Issue by vincenttschanz** [Astonex/Antox#676]
I tried to send a message to an offline uTox client, the message on Antox appeared  on a lighter background. 
When the other contact came back online, the message was not sent.

**Comment by LumenTeun** [comment]
This repo is no longer maintained. Check the [readme](https://github.com/Astonex/Antox#this-project-is-no-longer-being-maintained-for-various-reasons-there-is-a-working-and-maintained-fork-of-antox-here).

**Comment by vincenttschanz** [comment]
Sorry, didn't pay attention this was another repo.
