### ISSUE TITLE
Uses way too much battery

### ISSUE THREAD

**Issue by lovetox** [Astonex/Antox#680]
I have an Galaxy S5 mini, and this App burned through the battery in 4-5 hours.

If you need more Information on how to fix this, willing to do what i can.

i need Tox on my phone :)

best wishes

**Comment by nachfuellbar** [comment]
The source of your battery usage is the high bandwidth usage of Tox p2p concept
Try disabling UDP; it will use TCP relays instead

Some issues about this:
https://github.com/subliun/Antox/issues/6
https://github.com/irungentoo/toxcore/issues/1251

**Comment by Astonex** [comment]
Create an issue here https://github.com/irungentoo/toxcore as that is where the problems lies, and maybe more issues will make the developer consider it to be more important.
