### ISSUE TITLE
transifex

### ISSUE THREAD

**Issue by aaannndddyyy** [Astonex/Antox#691]
As of now, there are still many avid translators donating their time to translate Antox on transifex. Please use it or close the project on transifex and pull the work done by the translators so that they have not worked in vain. I have looked and you are having almost daily updates there, by 80 translators supporting Antox.

It is bad practise to solicit help and then discard it for no apparent reason.
Thx

**Comment by fireflystorm** [comment]
Hey aaannndddyyy can you explain what has happened?

Are you saying that basque language was removed from Transifex even though it has been translated?

I find Transifex by far the easies way to translate the project. The great thing is files can then be easily downloaded and merged into the source code.

**Comment by aaannndddyyy** [comment]
@fireflystorm : afaik, @Astonex is the one in charge of transifex for Antox, but Astonex is not maintaining Antox any longer, @subliun took over.
Since the move from Astonex to subliun quite some time ago now, that transifex translations were not used anymore. And transifex was deprecated for Antox' translation ( https://github.com/subliun/Antox/commit/14e983bf25fc58f8edb3df5295eb49189fdf70b4 ) , without the transifex Antox project bing closed, which leads to translators going on wokring on it.

Up until a few days ago when finally translations were pulled for the ifrst time, the transifex translations were never actually used anymore. 
This is a waste of ressources. Even if not all 80 translators are active, I have seen more translations going on after the (likely final) pull for at least four languages.

And no, I did not say Basque was removed from transifex. Afaic, there was never a transifxe Vasque translation of Antox. But there was a PR here, I only wondered why the PR was withdrawn, therefore I asked. So that was not related to this issue here.

**Comment by fireflystorm** [comment]
Astonex is not in charge of Transifex. I created and still maintain the transifex account. I can reliquish control if that is an issue.

When we swtiched from old Antox to the new I repointed the resources so that they are always in sync with the current Antox development.

It is true that I have not submitted a merge request to get all translations over but as you mention some recently did so.

I, too, agree that we should keep transifex and ask people to translate there. Transifex allows non developers to be able to contribute.

Let's not close it but rather used it more and educate people it is there they should translate.

**Comment by Astonex** [comment]
I have linked this issue to subliun so he can see it and hopefully get the transifex translations into the app

**Comment by subliun** [comment]
>Astonex is not in charge of Transifex. I created and still maintain the transifex account. I can reliquish control if that is an issue.

Well nobody told me. :P

Nice to meet you, @fireflystorm. I suppose we can continue using Transifex, though it would be nice if I had some sort of control over it. I've merged the latest translations thanks to @zetok.

**Comment by fireflystorm** [comment]
Sure set up an account on Transifex and send me a private message with the id.

**Comment by aaannndddyyy** [comment]
Ok, thank you.
I initially thought, that Astonex also had set up the transifex project and since he has stopped developing Antox and nobody included the work from transifex in subliun's Antox, plus the deletion of the mention of transifex in subliun's source, I thought Astonex should close the transifex project as no one wants to use it.
Turns out, it was not Astonex but fireflystorn who is in charge. And @fireflystorm seems not to have abandoned it. :)

This ticket is about either using the transifex work or closing the project there; and since there seems to be consensus now on using it, the issue is resolved.

Frankly, I don't know if one needs special privs in order to pull all translations at once, or if anybody can do it. As long as there are regular PR's that incorporate the translators' work so that it is not wasted, I'm happy with it. Even monthly PR from @fireflystorm could be enough. I just don't want to see translators dedicating many hours to translation work which then is never used at all.
Thank you all for your time and work. 
-closing-
